Ramana2596/project-game

src/constants/globalConstants.js
src/pages/NavigationMenu/GameNavigationMenu.jsx
src/pages/PartInfo/PartInfo.jsx
src/pages/PartInfo/constants/pageConstants.js

added partinfo page changes

---

src/constants/globalConstants.js

PartInfo: Changed from "UI 2110" to "UI 22 010"

PartInfo: UI Id Changed for Part Details Card

---

src/constants/globalConstants.js
src/pages/MarketInputError/MarketInputError.jsx
src/pages/MarketInputError/constants/pageConstants.js
src/pages/MarketInputError/services/service.js
src/pages/NavigationMenu/GameNavigationMenu.jsx
src/pages/OperationInputError/OperationInputError.jsx
src/pages/OperationInputError/constants/pageConstants.js
src/pages/OperationInputError/services/service.js

UI Page, UI 22 270 : - 100% Display Info
Screen Display, Api Call and data display tested Okay
Reference: UI Page: OperationInputError

New: UI Page MarketInputError  added

---

src/constants/globalConstants.js
src/pages/ProductMstInfo/constants/pageConstants.js

Category Id and PLM Stage deleted in Product Info. 
Label "Strategy Plan Approval" is changed to "Strategy Plan Decision"

Simple terms used in Info / Label

---

src/constants/globalConstants.js
src/pages/AssetCatalogBatch/AssetCatalogBatch.jsx
src/pages/AssetCatalogBatch/constants/pageConstants.js
src/pages/AssetCatalogBatch/services/service.js
src/pages/AssetCatalogTeam/constants/pageConstants.js
src/pages/NavigationMenu/GameNavigationMenu.jsx

New UI Screen  UI 22 010 Page: AssetCatalogBatch and UI 22 011 Page: AssetCatalogTeam are added
Column Headings in respective pageConstants corrected and Unwanted Column are "hidden".
Path and Components added in globalConstants
Path and Route added in NavigationMenu
Test:
API Calls are okay
Browser hosted the pages and data rendered -- OKAY

New UI Screen  UI 22 010 Page: AssetCatalogBatch and UI 22 011 Page: AssetCatalogTeam 

---

src/constants/globalConstants.js

Capital Asset Catalog (Master & Team) :
UI_Id , Label and display sequence are updated

UI Screen Capital Asset Catalog )updated 

---

src/constants/globalConstants.js
src/pages/NavigationMenu/GameNavigationMenu.jsx

import , components of Asset Catalog, (Team & Batch) and StdMarketInputNew are invoked.
import and element are invoked in GameNavigationMenu

globalConstants and GameNavigactionMenu

---

src/pages/ProductMstInfo/constants/pageConstants.js

Column Heading Changed  to 'Estd Price'

ProductMstInfo:

---

src/constants/globalConstants.js
src/pages/ProductMstInfo/constants/pageConstants.js

Label name changed as per user feedback

New changes

---

src/pages/StdMarketInputNew/StdMarketInputNew.jsx

Using preliminary code,  added feature of selecteable gameBatch. For use as reference for similar needs

UI StdMarketInputNew

---

src/constants/globalConstants.js

New UI Screen ID used for 
User Mgt Desk and 
System Info Desk,

UI Screen no  for Hamburger updated

---

src/pages/SignIn/SignIn.jsx

While updating to correct async in setState and actual update of data, the top code lines on import etc., were commented first and then deleted by mistake.
So it is restored from back signIn.jsx

Restored import, Card, SignInContainer from backup of signIn.jsx.

---

src/pages/FeatureManagement/components/GameTeamPlay.jsx

UI GameTeamPlay

---

src/pages/StrategyPlanApproval/services/strategyPlanApprovalService.js
src/pages/UserProfileInfo/UserProfileInfo.jsx
src/pages/UserProfileInfo/constants/pageConstants.js

StrategyPlanApproval 
Parameter @CMD_Line added, matching SP, 
userProfileInfo: 
Updated for enabling hiddencolumns in userProfileInfo.jsx and pageConstants
Test: Opens in bowser and display is okay

StrategyPlanApproval (for CMD_Line) and userProfileInfo ( for hidden columns)

---

src/pages/MarketFactorInfo/constants/pageConstants.js
src/pages/MarketInfoTeam/MarketInfoTeam.jsx
src/pages/MarketInfoTeam/constants/pageConstants.js

Hidden column option addeed in UIMarketInputInfo and MarketFactoinfo"

UI MarketInfoInput

---

src/pages/RegisterUser/EnrollDialog.jsx
src/pages/RegisterUser/RegisterPage.jsx
src/pages/RegisterUser/RegistrationForm.jsx
src/utils/statusCodes.js

1) Improvement : Modular components are coded as separate file
Form for Registering User Profile
Enroll Dialog
API_STATUS as generic function
2) RegisterPage.jsx  modified accordingly:
a)  import of modular components: 
Form, Dialog, API_Satus and AlertData
b) Old code lines removed. New functions are called
3) Test:
App opens in browser.
Form and dialogs deployed.
Navigation is okay.
Registering new-user profile and Enrolment are okay

UI RegisterForm

---

src/core/access/userContext.js

Added user info userId, LoginId, learnMode,- matching setGameInfo

Core / Access /userContext

---

src/pages/RegisterUser/RegisterPage.jsx

RegisterPage. and enrollUserDialog are now modular and reusable.

UI Register

---

src/pages/IncomeStatementInfo/IncomeStatementInfo.jsx
src/pages/IncomeStatementInfo/constants/pageConstants.js

Added HighlightRowsbyDetails - to mark the vitalRows of table data 'bold'

incomeStamentInfo-   Added HighlightRowsbyDetails 

---

src/pages/BalanceSheetInfo/BalanceSheetInfo.jsx
src/pages/BalanceSheetInfo/constants/pageConstants.js

balanceSheetInfo:
-- Added HighlightbyRows to mark the listed vital rows in bold.
pageConstants:
-- List of vitalRows
Test: OKAY
App opens in browser.
The VitalRows are displayed in bold letters

UI BalanceSheetInfo

---

src/pages/CasFlowStatement/CasFlowStatement.jsx
src/pages/CasFlowStatement/constants/pageConstants.js

Added HighligntbyRows to mark the lsited vital rows in bold.
CashFlowStatement.jsx:
--- Under GenericTable: added HighligntbyRows
pageConstants.js 
-- Added List of vitalRows
Test: OKAY
App opens in browser.
The VitalRows are displayed in bold letters

UI CashFlowStatement

---

src/pages/RegisterUser/EnrollUserDialog.jsx

UI EnrollUserDialog

---

src/pages/RegisterUser/RegisterPage.jsx

UI RegisterUser

---

src/constants/globalConstants.js

Corrected TYpo Error : file suffix .jsx added

 globalConstants

---

src/pages/StrategyPlanApproval/StrategyPlanApproval.jsx

success msg; changed "Approval" to "Decision"

UI StrategyPlan

---

src/pages/OperationalPlanInfoInput/OperationalPlanInfoInput.jsx
src/pages/OperationalPlanInfoInput/components/OperationalPlanInputTable.jsx

Better use of Vertical Space of the Form
1. Added Bottom margin for Batch & team
2. Set Bottom Margei zero for Drop Box of Operation Input and Period 
3. Recuded Margin for Buttons
4. added margin for Divider
Test: Form on Laptp !5 inch Dislay is OKAY

UI Screen Operation Decision Input - Reduced white spaces & Auto Vt. scrollbar

---

src/pages/SimulationPlay/SimulationPlay.jsx
src/pages/SimulationPlay/constants/pageConstants.js
src/pages/SimulationPlay/services/service.js

Added as a new UI Screen Card  component, in lieu of TeamPlay as Accordian component

UI Screen : SimulationPlay

---

src/constants/globalConstants.js
src/pages/NavigationMenu/GameNavigationMenu.jsx

Simulation Play:
in globalConstants and GameNavigationMenu
import, component and element  are added.
Existing "TeamPlay" is commented

globalConstants
